# Instalación Go
# ansible-playbook -i inventory.cfg 50_go.yml

- hosts: localhost
  become: false
  gather_facts: false

  vars:
    GO: 1.12
    SRC: "$HOME/.develop-host/go-{{ GO }}"
    DEST: "/usr/local/golang/{{ GO }}"

  tasks:
    - name: Create Folder
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ SRC }}"
        - "{{ DEST }}"

    - name: Download
      get_url:
        url: "https://storage.googleapis.com/golang/go{{ GO }}.linux-amd64.tar.gz"
        dest: "~/.develop-host/go{{ GO }}.linux-amd64.tar.gz"

    - name: Unarchive File
      unarchive:
        src: ~/.develop-host/go{{ GO }}.linux-amd64.tar.gz
        dest: "{{ SRC }}"
        remote_src: yes

    - name: Copy
      command: "cp -r {{ SRC }}/go {{ DEST }}"
      args:
        creates: "{{ DEST }}/go"

    - name: List Bin
      command: "ls {{ DEST }}/go/bin"
      changed_when: false
      register: list_bin

    - name: Create Links
      file:
        state: link
        src: "{{ DEST }}/go/bin/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
      with_items: "{{ list_bin.stdout_lines }}"

    - name: Create Go ROOT Link
      file:
        state: link
        src: "{{ DEST }}/go"
        dest: "/usr/local/go"
