# Instalación Java
# ansible-playbook -u root -i inventory.cfg 53_java.yml

- hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Install Oracle Java
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openjdk-8-jdk
        - openjdk-8-jre

    - name: Correct Java Version Selected
      alternatives:
        name: java
        path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
