# Instalación Flutter
# ansible-playbook -u root -i inventory.cfg 54_flutter.yml

- hosts: localhost
  become: false
  gather_facts: false

  vars:
    VERSION: 1.2.1
    DEST: "/usr/local/flutter/{{ VERSION }}"
    SRC: "$HOME/.develop-host/flutter-{{ VERSION }}"

  tasks:
    - name: Create Folder
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ SRC }}"
        - "{{ DEST }}"

    - name: Download
      get_url:
        url: "https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v{{ VERSION }}-stable.tar.xz"
        dest: "~/.develop-host/flutter_linux_v{{ VERSION }}-stable.tar.xz"

    - name: Unarchive File
      unarchive:
        src: ~/.develop-host/flutter_linux_v{{ VERSION }}-stable.tar.xz
        dest: "{{ SRC }}"
        remote_src: yes

    - name: Copy
      command: "cp -r {{ SRC }}/flutter {{ DEST }}"
      args:
        creates: "{{ DEST }}/flutter"

    - name: List Bin Flutter
      command: "ls {{ DEST }}/flutter/bin"
      changed_when: false
      register: list_bin

    - name: Create Links Flutter
      file:
        state: link
        src: "{{ DEST }}/flutter/bin/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
      with_items: "{{ list_bin.stdout_lines }}"

    - name: Permissions Exec
      file: 
        path: "{{ item.p }}"
        mode: "{{ item.m }}"
      with_items:
        - { p: "{{ DEST }}/flutter/bin/cache/dart-sdk/bin", m: 755 }
        - { p: "{{ DEST }}/flutter/bin/cache/flutter_version_check.stamp", m: 666 }
        - { p: "{{ DEST }}/flutter/bin/cache/lockfile", m: 666 }
        - { p: "{{ DEST }}/flutter/version", m: 666 }

    - name: List Bin Dart
      command: "ls {{ DEST }}/flutter/bin/cache/dart-sdk/bin"
      changed_when: false
      register: list_bin

    - name: Create Links Dart
      file:
        state: link
        src: "{{ DEST }}/flutter/bin/cache/dart-sdk/bin/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
      with_items: "{{ list_bin.stdout_lines }}"
